name: 'subcr-avd-tst-001'

parameters:
- name: environment
  displayName: 'Environment to deploy to'
  type: string
  default: 'test'
  values:
  - test
  - integration
  - trn

variables:
- group: AVD-Canary-Config

# Environment specific variable files
- ${{ if eq(parameters.environment, 'test') }}:
  - template: pipeline.variables.tst.yml

- ${{ if eq(parameters.environment, 'integration') }}:
  - template: pipeline.variables.integration.yml

- ${{ if eq(parameters.environment, 'trn') }}:
  - template: pipeline.variables.trn.cmp.yml

pool:
  name: $(poolName)

trigger: none

stages:
- stage: Validation
  condition: succeeded()
  jobs:
  - deployment: Template_Validation
    displayName: 'Baseline validation'
    environment: $(devOpsPipelineEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(serviceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              useGlobalConfig: false
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              inlineScript: |
                az --version
                az deployment sub what-if \
                  --location $(location) \
                  --template-file $(System.DefaultWorkingDirectory)/$(templatePath) \
                  --parameters $(System.DefaultWorkingDirectory)/$(parametersPath) \
                  --parameters avdVmLocalUserPassword="$(avdVmLocalUserPassword)"

- stage: Deployment
  dependsOn:
  - Validation
  condition: succeeded('Validation')
  jobs:
  - deployment: Template_Deployment
    displayName: 'Baseline deployment'
    environment: $(devOpsPipelineEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              environment: '$(devOpsPipelineEnvironment)'
              azureSubscription: '$(serviceConnection)'
              scriptType: bash
              scriptLocation: inlineScript
              useGlobalConfig: false
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              inlineScript: |
                az deployment sub create \
                  --location $(location) \
                  --template-file $(System.DefaultWorkingDirectory)/$(templatePath) \
                  --parameters $(System.DefaultWorkingDirectory)/$(parametersPath) \
                  --parameters avdVmLocalUserPassword="$(avdVmLocalUserPassword)"
